
using System.Reflection;


// This code was generated by a tool from CustomVersionNumber.tt. Any changes made manually will be lost
// the next time this code is regenerated.
// path          = C:\Users\David\Documents\_Code\cSharp\HelloDCOM1\HelloDCOM1\CustomVersionNumber.cs
// output.Length = 547
// matches       = 1
// version was   = 2018.325.1948.2
// built at local and utc date 3/25/2018 4:12:59 PM 3/25/2018 8:12:59 PM
[assembly: AssemblyVersion("2018.1803.0325.2012")]
[assembly: AssemblyFileVersion("2018.0325.2012.3")]
