CREATE TABLE [dbo].[CIM_ACL_ACE] (
    [Id]    INT IDENTITY (1, 1) NOT NULL,
    [ACLID] INT NOT NULL,
    [ACEID] INT NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
CREATE UNIQUE NONCLUSTERED INDEX [ixCIMACLACE]
    ON [dbo].[CIM_ACL_ACE]([ACLID] ASC, [ACEID] ASC);

